email = "50436249+kryota-dev@users.noreply.github.com"
signingkey = "~/.ssh/ssh-key.pub"
name = "kryota-dev"
ghq_user = "kryota-dev"

[versions]
  moralerspace_font = "2.0.0"

[skills]
  anthropic_commit = "57546260929473d4e0d1c1bb75297be2fdfa1949"
