#!/bin/bash
# Claude Code hook -> wave-orchestrator event recorder (kryota-dev/dotfiles#437).
#
# Wired in settings.json for Notification / PreToolUse(AskUserQuestion) / Stop /
# UserPromptSubmit. Reads the hook payload on stdin and appends it verbatim to a
# per-session file, so the orchestrator can tell "this child stopped and is
# waiting" without scraping the TUI.
#
# Why not scrape the pane: matching on screen text broke three different ways in
# practice (#435 wrong marker, #436 stale scrollback matched as "busy" and the
# stop was silently missed, #438 a queued-message placeholder read as unsent).
# The payload carries notification_type and the full AskUserQuestion input, so
# the orchestrator never has to guess from rendered text.
#
# Fail-open contract (async hook, timeout 10): every exit path is 0. A missing
# jq, an unwritable state dir, or a malformed payload must never block the
# session. The *reading* side is fail-safe instead: no events means UNKNOWN, not
# "still running" (see scripts/wave-events.sh).
#
# session_id lands in a filename, so it is validated as a UUID before use. The
# payload is generated by Claude Code and is normally a UUID, but the value is
# treated as untrusted input: anything else (e.g. a path traversal attempt) is
# dropped rather than written.
set -euo pipefail

EVENT_DIR="${WAVE_EVENT_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/wave-orchestrator/events}"

UUID_RE='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'

main() {
  # No jq (unprovisioned machine) -> silent no-op rather than a broken hook.
  command -v jq >/dev/null 2>&1 || return 0

  local input session_id
  input="$(cat 2>/dev/null || true)"
  [ -n "$input" ] || return 0

  session_id="$(printf '%s' "$input" | jq -r '.session_id // empty' 2>/dev/null || true)"
  [ -n "$session_id" ] || return 0
  printf '%s' "$session_id" | grep -qE "$UUID_RE" || return 0

  # 077 makes the dir 700 and the file 600: the payload carries conversation
  # content (question text and option labels), same sensitivity as a transcript.
  umask 077
  mkdir -p "$EVENT_DIR" 2>/dev/null || return 0

  # One payload per line. Per-session files keep concurrent writers from
  # interleaving, which a single shared file could not guarantee.
  printf '%s\n' "$input" >>"${EVENT_DIR}/${session_id}.jsonl" 2>/dev/null || return 0
}

main || true
exit 0
