#!/bin/bash
# Claude Code hook -> wave-orchestrator event recorder (kryota-dev/dotfiles#437).
#
# Wired in settings.json for Notification / PreToolUse(AskUserQuestion) / Stop /
# UserPromptSubmit / PostToolUse(AskUserQuestion) / PostToolUseFailure(AskUserQuestion) /
# StopFailure. Reads the hook payload on stdin and appends it to a per-session
# file, so the orchestrator can tell "this child stopped and is waiting"
# without scraping the TUI.
#
# Recording is projected per event type: only the fields the reading side
# actually consumes are kept, so conversation text never lands on disk (#474,
# #477). The projections deliberately differ -- reusing one allowlist would drop
# UserPromptSubmit's permission_mode, which the reader needs to classify
# permission_prompt notifications (#443 / #486). Event types not listed in the
# case below (PreToolUse, Stop, StopFailure) are still appended verbatim: the
# reader needs PreToolUse's full tool_input to render the pending question.
#
# Why not scrape the pane: matching on screen text broke three different ways in
# practice (#435 wrong marker, #436 stale scrollback matched as "busy" and the
# stop was silently missed, #438 a queued-message placeholder read as unsent).
# The payload carries notification_type and the full AskUserQuestion input, so
# the orchestrator never has to guess from rendered text.
#
# Fail-open contract (async hook, timeout 10): every exit path is 0. A missing
# jq, an unwritable state dir, or a malformed payload must never block the
# session. The *reading* side is fail-safe instead: no events means UNKNOWN, not
# "still running" (see scripts/wave-events.sh).
#
# session_id lands in a filename, so it is validated as a UUID before use. The
# payload is generated by Claude Code and is normally a UUID, but the value is
# treated as untrusted input: anything else (e.g. a path traversal attempt) is
# dropped rather than written.
#
# Opt-in only: the hook is wired for every session, but records nothing unless
# WAVE_ORCHESTRATOR_SESSION is set in the environment (the orchestrator exports
# it when launching a child). Without this gate every ordinary session would
# persist its question text and option labels, which is a side effect the
# feature never asked for.
set -euo pipefail

EVENT_DIR="${WAVE_EVENT_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/wave-orchestrator/events}"

UUID_RE='^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'

main() {
  # Not a wave child -> record nothing. Ordinary sessions must not accumulate
  # conversation content just because the hook is wired globally.
  [ -n "${WAVE_ORCHESTRATOR_SESSION:-}" ] || return 0

  # No jq (unprovisioned machine) -> silent no-op rather than a broken hook.
  command -v jq >/dev/null 2>&1 || return 0

  local input session_id hook_event_name jq_ids
  input="$(cat 2>/dev/null || true)"
  [ -n "$input" ] || return 0

  # session_id and hook_event_name in one jq call: the former gates the
  # filename, the latter picks verbatim vs. projected below.
  # `// ""` (not `// empty`) keeps both positions: `empty` drops the element and
  # would shift hook_event_name into session_id when session_id is missing.
  jq_ids="$(printf '%s' "$input" | jq -r '[.session_id // "", .hook_event_name // ""] | @tsv' 2>/dev/null || true)"
  [ -n "$jq_ids" ] || return 0
  IFS=$'\t' read -r session_id hook_event_name <<<"$jq_ids"

  [ -n "$session_id" ] || return 0
  printf '%s' "$session_id" | grep -qE "$UUID_RE" || return 0

  # 077 makes the dir 700 and the file 600: the payload carries conversation
  # content (question text and option labels), same sensitivity as a transcript.
  umask 077
  mkdir -p "$EVENT_DIR" 2>/dev/null || return 0

  local filter=""
  case "$hook_event_name" in
    PostToolUse | PostToolUseFailure)
      # Terminal AskUserQuestion events carry tool_response, which holds the
      # user's answer text. The reader only needs the correlation fields to
      # pair these against PreToolUse's tool_use_id.
      filter='{session_id, prompt_id, hook_event_name, tool_name, tool_use_id}'
      ;;
    UserPromptSubmit)
      # `prompt` is the user's free-form instruction for the turn and is never
      # read back. `permission_mode` is load-bearing and must stay: it is the
      # only place the reader can learn the turn's mode, because Notification
      # payloads do not carry it (measured). Dropping it would break the
      # permission_prompt classification (#443 / #486).
      filter='{session_id, prompt_id, hook_event_name, permission_mode}'
      ;;
    Notification)
      # `message` is the rendered notification text; the reader classifies on
      # notification_type alone and never reads prose (#435). permission_mode is
      # kept because it is load-bearing whenever present -- today it is absent,
      # so this projects to null, which the reader's `// empty` already drops.
      filter='{session_id, prompt_id, hook_event_name, notification_type, permission_mode}'
      ;;
  esac

  if [ -n "$filter" ]; then
    # Projection failure means don't write, matching the fail-open contract
    # above: a payload we could not project must not be persisted verbatim.
    local projected
    projected="$(printf '%s' "$input" | jq -c "$filter" 2>/dev/null || true)"
    [ -n "$projected" ] || return 0
    printf '%s\n' "$projected" >>"${EVENT_DIR}/${session_id}.jsonl" 2>/dev/null || return 0
  else
    # One payload per line. Per-session files keep concurrent writers from
    # interleaving, which a single shared file could not guarantee.
    printf '%s\n' "$input" >>"${EVENT_DIR}/${session_id}.jsonl" 2>/dev/null || return 0
  fi
}

main || true
exit 0
