name: Actions Lint
on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
      pull-requests: write
    uses: kryota-dev/actions/.github/workflows/actions-lint.yml@b72de173fed12f43bada4257182e977b750495d8 # v0.2.5
