name: Actions Lint
on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
      pull-requests: write
    uses: kryota-dev/actions/.github/workflows/actions-lint.yml@a90284f8283e93f69308dfa2f1153fd47440fea3 # v0.2.1
