name: Actions Lint
on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**/*.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
      pull-requests: write
    uses: kryota-dev/actions/.github/workflows/actions-lint.yml@1b0a97fd1b3e970f119d09fd2949be8d7fc45959 # v0.2.4
