name: Setup PR
on:
  pull_request:
    branches: [main]
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  auto-assign:
    permissions:
      pull-requests: write
    uses: kryota-dev/actions/.github/workflows/auto-assign-pr.yml@f8009e36b4c6db991e969e3052b87ee8c6577531 # v0.2.3
    with:
      bot-assignees: "kryota-dev"
