name: Setup PR
on:
  pull_request:
    branches: [main]
    types: [opened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  auto-assign:
    permissions:
      pull-requests: write
    uses: kryota-dev/actions/.github/workflows/auto-assign-pr.yml@1b0a97fd1b3e970f119d09fd2949be8d7fc45959 # v0.2.4
    with:
      bot-assignees: "kryota-dev"
