name: Setup PR
on:
  pull_request:
    branches: [main]
    types: [opened]

permissions: {}

jobs:
  auto-assign:
    permissions:
      pull-requests: write
    uses: kryota-dev/actions/.github/workflows/auto-assign-pr.yml@a90284f8283e93f69308dfa2f1153fd47440fea3 # v0.2.1
    with:
      bot-assignees: "kryota-dev"
